### ISSUE TITLE
Support for hdf5 1.14

### ISSUE THREAD

**Issue by ndjensen** [PyTables/PyTables#1025]
Hi, what releases of pytables work with hdf5 1.14?  I couldn't find reference to hdf5 1.14 in the documentation or release notes.

**Comment by avalentino** [comment]
Dear @ndjensen it is not clear to me what is the purpose of your question.
Do you have any specific issue with HDF5 v1.14?

PyTables currently uses HDF5 exploiting the compatibility layer for HDF5 v1.8 (`H5_USE_18_API`) hence it should be compatible with all HDF5 versions newer than v1.8 that do not break that compatibility, including v1.14.

The current stable version of PyTables (v3.8) requires `HDF5>=1.10.5`, and the corresponding binary `wheel`s, currently on PyPI, have been built using HDF5 v1.12.2.
 
The current development version (git `master` branch) exploits some very recent features (`H5Dchunk_iter`) and requires HDF5 >= 1.14.

Finally, information about the minimum supported version of the C libraries used by PyTables can be found in:
* in the [userguide](http://www.pytables.org/usersguide/installation.html#prerequisites) online
* ot the corresponding [RST source](https://github.com/PyTables/PyTables/blob/master/doc/source/usersguide/installation.rst#prerequisites) in git
* the [tables/req_versions.py](https://github.com/PyTables/PyTables/blob/master/tables/req_versions.py) file

Please let me know if you this answers to your question.

**Comment by ndjensen** [comment]
Yes, that answers my question, thank you.  A project I work on has an issue with hdf5 1.12 and is considering upgrading to 1.14 and I wanted to make sure PyTables would continue to work.  It sounds like thanks to PyTables making use of the hdf5 1.8 compatibility layer that everything will be fine.

You can close this issue if you want.  Thank you for your help.

**Comment by avalentino** [comment]
@ndjensen thanks for the feedback

**Comment by hhalaby** [comment]
Hello @avalentino, I have some similar errors while installing and wanted to understand a bit more. Any answer would be greatly appreciated !

I have the following behavior:
|Tables|Python|Error|
|-|-|-|
|v3.7.0|3.11.6|`ERROR: Failed building wheel for tables` - expected|
|v3.9.0|3.11.6|No Error|
|pip3 install git+https://github.com/PyTables/PyTables|3.11.6|`ERROR:: Unsupported HDF5 version! HDF5 v1.10.5+ required. Found version v1.10.4`|

Is the difference in behavior between `v3.9.0` and `main` due to the fact that building requires a newer HDF5 version but installing a release version already has everything packaged ? Should I expect any issue from using `Tablesv3.9.0` with Python3.11.6 because of `HDF5v1.10.4` ?

**Comment by FrancescAlted** [comment]
HDF5>=1.10.5 is required so as to use `H5Dget_chunk_info()`, which is necessary for the blosc2 plugin (introduced in PyTables 3.8.0).  So yes, you need it for compiling PyTables >= 3.8.0.  If your system does not complain when installing v3.9.0, it is probably because your pip is downloading the binary wheel (compiled internally with HDF5 1.14.2) under the hood.
