### ISSUE TITLE
Performance issue at import time on Ubuntu

### ISSUE THREAD

**Issue by anttimc** [PyTables/PyTables#1081]
I noticed a performance issue on Ubuntu with `cpuinfo.get_cpu_info()`. It causes pytables 3.9.1 import to slow down by approximately one second compared to 3.8.0.

The details of the issue are described here: https://github.com/workhorsy/py-cpuinfo/issues/205

**Comment by avalentino** [comment]
This should be fixed via #1091.
Please feel free to re-open if you still have problems.

**Comment by anttimc** [comment]
The issue seems to have been moved from import time to run time. So I think https://github.com/PyTables/PyTables/pull/1091 will not fix the issue if cpu_info is still required (and not optional) dependency.

The real root cause should be fixed on cpu_info side, though.

**Comment by avalentino** [comment]
@anttimc not sure to follow you comment.

The title of the issue refers to "import time" and I think that that issue is indeed solved IMHO.

I agree with you that when you need to compute automatically the optimum chunk shape you still need to import `cpu_info` and hence you experiment the delay cause by `cpu-info` itself.
By the way, the situation is now better then before because we only spend that time if it is really needed and we only do it once (being the result of the operation cached).

It is not totally clear what you are suggesting now.

From my point of view to improve the situation further se have 2 options:

1. do not use `cpu-info` at all. This could lead to worse `chunkshape` values. I'm open to discussion and to review a PR.
2. make `cpu-info` faster. In this case it is not a PyTables issue, we should move the discussion to a dedicated issue on `cpu-info` itself.

So I miss something?

**Comment by anttimc** [comment]
You're correct, the performance issue _at import time_ is solved by the PR. According to the changes in the PR performance issue of `cpuinfo.get_cpu_info()` is now at run time when calling `Leaf._calc_chunkshape` and I think that method is called when opening a file for the first time, right?

1. How essential an optimal `chunkshape` is to the overall performance? I have no idea. In pytables version 3.8.0, `Leaf._calc_chunkshape` does not use `cpuinfo` , and the overall performance is acceptable. https://github.com/PyTables/PyTables/blob/e34d1f78ed905694672c49a33ef3004a2f8899f2/tables/leaf.py#L310
2. I have already opened an issue in `cpuinfo` https://github.com/workhorsy/py-cpuinfo/issues/205 as mentioned in the original post. Let's hope it gets some attention.

**Comment by avalentino** [comment]
> You're correct, the performance issue _at import time_ is solved by the PR. According to the changes in the PR performance issue of `cpuinfo.get_cpu_info()` is now at run time when calling `Leaf._calc_chunkshape` and I think that method is called when opening a file for the first time, right?

If I remember correctly it should be called only when you *create* an new dataset.
If you open a dataset to read it, then the `chuncshape` is the one defined in the dataset itself.

> 1. How essential an optimal `chunkshape` is to the overall performance? I have no idea. In pytables version 3.8.0, `Leaf._calc_chunkshape` does not use `cpuinfo` , and the overall performance is acceptable. https://github.com/PyTables/PyTables/blob/e34d1f78ed905694672c49a33ef3004a2f8899f2/tables/leaf.py#L310

Recently a very optimised mechanism to access HDF5 data leveraging blosc2 has been introduced. The change you mention has been introduced at that stage because to achieve outstanding performance you need to choose the `chunkshape` properly.
By the way I cannot say how much you lose if you go back to the old approach. 
Maybe @FrancescAlted or @ivilata can comment about it.

**Comment by FrancescAlted** [comment]
I introduced that because our experiments shown that using the L3 efficiently is one of the major factors in improving compression/decompression performance.  It is unfortunate that `cpuinfo.get_cpu_info()` is so expensive, and I very much prefer this to be fixed in the `cpuinfo` package.  Having said that, if this cannot be fixed upstream, one could go back to the old approach (and let users find the optimal size).

**Comment by anttimc** [comment]
I started to profile `cpuinfo` myself as there were no responses to the issue.

It seems that there is a **one-second sleep** in a function that estimates the raw hz of the processor. See this comment https://github.com/workhorsy/py-cpuinfo/issues/205#issuecomment-1833653828

**Comment by anttimc** [comment]
I read a bit more about blosc2, and indeed there's a big performance boost to be expected. If I have time I'll try to contribute with a PR to `cpuinfo` to refactor and parameterize `get_cpu_info` so that we could get the CPU cache size quickly with out any extra info. However, so far the maintainer(s) of cpuinfo have not replied to the [issue](https://github.com/workhorsy/py-cpuinfo/issues/205#issue-1994357956).

I noticed that the default compression library is actually still `zlib` https://www.pytables.org/_modules/tables/filters.html

I wonder if there could be an intermediate solution of using `cpuinfo` only if blosc2 is used (I don't how hard this would be technically)? But let's hope thing move forward with `cpuinfo` and no intermediate solutions would be needed.

**Comment by avalentino** [comment]
Thanks @anttimc, we are open to discussion.

**Comment by FrancescAlted** [comment]
A somewhat wild idea: what about caching the values for cpuinfo in the local filesystem (say, $HOME/.pytablesrc) and populate this only once; after that, there should no need to call cpuinfo anymore.
I think most of the codecs would benefit from this, but we can opt for doing this for Blosc2 only and remove the need to do that in PyTables; I am open to receive PRs in python-blosc2 (and use $HOME/.blosc2rc).
