### ISSUE TITLE
Update dependency constraints for NumPy 2.0.0

### ISSUE THREAD

**Issue by jakirkham** [PyTables/PyTables#1200]
Thanks for all of your work (especially on NumPy 2 compatibility)! 🙏

Was just noticing that packages are currently constrained to installing on NumPy 1

Think we would want to relax this to `>= 1.20.0`

https://github.com/PyTables/PyTables/blob/13ee9ac0dfe231b1e96ab3c1c53ed2c6dfd5ad20/pyproject.toml#L70-L71

Also would suggest using NumPy 2 during the build. So changing 1.20.0 to 2.0. The resulting binaries will be compatible with NumPy 1 & 2 (even though they are built with NumPy 2)

https://github.com/PyTables/PyTables/blob/13ee9ac0dfe231b1e96ab3c1c53ed2c6dfd5ad20/pyproject.toml#L1-L8

Sorry to bring this up right after a release 😞

**Comment by ivilata** [comment]
No worries @jakirkham, and thanks a lot for the report. For some reason I was under the wrong impression that the wheels were already being built against NumPy 2, I should have checked twice. Sorry for the inconveniences!

**Comment by avalentino** [comment]
Ah, sorry. For some reason I forgot to update the `dependencies` in `pyptoject.toml`.
The testing should be already fine because at least in one of our CI test we ignore the dependency check.

Regarding the `build-system`, using `numpy >= 1.20` is intentional because we want to allow builds in environments where  numpy2 is not available (at leas for this release).
In common cases the latest numpy version should be selected automatically so the current status should be already fine from my point of view.

@jakirkham do you agree?

> @avalentino, should this be added to the v3.10.1 milestone?

IMHO yes.
If needed I can work on it in the coming days.

**Comment by jakirkham** [comment]
> Ah, sorry. For some reason I forgot to update the `dependencies` in `pyptoject.toml`. The testing should be already fine because at least in one of our CI test we ignore the dependency check.
> 
> Regarding the `build-system`, using `numpy >= 1.20` is intentional because we want to allow builds in environments where numpy2 is not available (at leas for this release). In common cases the latest numpy version should be selected automatically so the current status should be already fine from my point of view.
> 
> @jakirkham do you agree?

While one can build against NumPy 2 to provide packages that support NumPy 1 & 2, that is not the case when building with NumPy 1. When building with NumPy 1, packages will only support NumPy 1

So this leaves us with an interesting situation, what should we design the requirements for?

1. Making it easy to build NumPy 1 & 2 compatible binaries (assume most users get binaries from us)
2. Merely point users to an escape hatch like [`--no-build-isolation`]( https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-no-build-isolation ) (as [SciPy does]( https://github.com/scipy/scipy/blob/8971d5e9b72931987b7d3c5a25da1a8e7e5485d0/pyproject.toml#L25-L31 ))
3. Allow users to [build with NumPy 1 or 2]( https://github.com/scikit-learn-contrib/hdbscan/blob/2e7112d3b8a65ebb94db95c24243d0c79ad8cfa5/pyproject.toml#L6 ) and [leave it to them fix the overly loose NumPy runtime constraint]( https://github.com/scikit-learn-contrib/hdbscan/blob/2e7112d3b8a65ebb94db95c24243d0c79ad8cfa5/requirements.txt#L1 )
4. ?

All of these have their own tradeoffs

As you have asked for my opinion, would lean towards 2 and maybe add another comment for the runtime constraint that would need a fix. Folks that are able to build from source are usually also capable of patching the source to meet their needs. Leaving some instructions for them though is a nice thing to do

**Comment by avalentino** [comment]
@jakirkham thanks for your feedback.
I think that we all agree on the need of fixing the runtime requirement:

https://github.com/PyTables/PyTables/blob/13ee9ac0dfe231b1e96ab3c1c53ed2c6dfd5ad20/pyproject.toml#L70-L71

In my plans that should become:

```diff
 dependencies = [ 
-    "numpy >= 1.20.0, <2", 
+    "numpy >= 1.20.0", 
```

Regarding build-system requirements my question was mostly in the direction of understanding if, from you point of view, the current version of the requirement is technically correct or not:

https://github.com/PyTables/PyTables/blob/13ee9ac0dfe231b1e96ab3c1c53ed2c6dfd5ad20/pyproject.toml#L1-L8

From my perspective requiring `numpy >= 2` would not be technically correct because PyTables can indeed be built with numpy 1.x.

I understand the advantages of using numpy 2 at build time but, from my perspective, this is not a good reason to prevent people from building PyTables in contexts where numpy 2 is not available.

Please consider that PyTables v3.10 comes with a full set of wheel packages, and that  such packages have been built using numpy 2.

Please also consider that, in a common situation, when people run `python3 -m build` to build PyTables they get the package built with the latest version of numpy (independently on the fact that we have enforced it in the build requirements)

**Comment by jakirkham** [comment]
Right the ideal case is if we could say

```python
numpy_run = "numpy>=1.20"
match numpy_build:
    case "numpy>=1.20,<2":
        numpy_run += ",<2"
    case "numpy>=2,<3":
        numpy_run += ",<3"
```

However AFAIK this is not possible to do today

So all the options I provided above were in some way "wrong". That said, as we can't capture the ideal behavior with what is available today, it becomes a matter of preference between the different error modes. IOW which do we pick?

1. An overly constrained build constraint that is sufficient for the loose runtime constraint (more work for NumPy 1 builds)
2. A more accurate build constraint with a loose runtime constraint (too loose in the NumPy 1 build case)

To be clear I don't think either of these choices is wrong. They are just different choices with different tradeoffs

It sounds like your preference is 2. Is that right? If so, would suggest going ahead

**Comment by FrancescAlted** [comment]
Sorry if I sound a bit disruptive here, but what if newest version of PyTables does not provide support for being compiled against NumPy 1.x? This should simply the building logic a lot, while still keeping binary builds compatible with NumPy 1.x (>1.20 should be fine with these builds). I am not a big fan of keeping support for old versions of dependencies: if there is people needing support for building with NumPy 1.x, they can always use older versions of PyTables (in the end, they worry about old stack).

**Comment by avalentino** [comment]
In this case I do not see a big simplification of the build logic linked to the change of numpy version constraint in the build requirements. Do I miss something?

In any case I do not want to insist.

I will prepare the patch later today and once it is merged I can also prepare an hotfix release if it is OK for everybody.

**Comment by FrancescAlted** [comment]
> In this case I do not see a big simplification of the build logic linked to the change of numpy version constraint in the build requirements. Do I miss something?

Sorry if I perceived a difficulty in providing building compatibility with NumPy 1.x; if that is not the case, then much better for everybody.

**Comment by avalentino** [comment]
No no, the implementation is the easy part
* If we use ` "numpy >= 1.20.0"` in build-system requirements we allow people to build with numpy 1.x but the risk is that if someone uses the produced SW with numpy 2 there will be an ABI compatibility issue.
* If we use ` "numpy >= 2"` in build-system requirements we loose the possibility to build with numpy 1.x but the produced SW will be ABI compatible both with numpy 1.x and 2.

I was arguing that the first case is, in any case, unlucky to happen but, as @jakirkham was saying we do not have a prefect solution, we just need to choose the option that we prefer

**Comment by FrancescAlted** [comment]
In that case, and for what is worth, I am in favor of using `numpy>=2` in build-system requirements to ensure ABI compatibility with NumPy 1 and 2. Users wanting to build with NumPy 1 can always use older versions of PyTables.

**Comment by avalentino** [comment]
Understood
As I said I will prepare the PR in the afternoon
