### ISSUE TITLE
Building a wheel with internal blosc enables AVX2 in CFLAGS

### ISSUE THREAD

**Issue by tomkooij** [PyTables/PyTables#627]
Current manylinux wheels build with `-mavx2`. This gcc flag is added by `setup.py` when the internal blosc is used and the cpu has AVX2 (as reported by the vendored `cpuinfo.py`)

This results in AVX (and probably AVX2) opcodes in `hdf5extension.so` which breaks simple hdf5 operations on many systems, as AVX2 is not supported on many (fairly recent) CPUs.

The setup.py behaviour is quite inconsistent: Only when the internal blosc is used are the CFLAGS `-mavx2` and `-msse2` (when available) added to **all** gcc calls.

From studying the output of a v3.3.0 wheel build (with external blosc lib) it seems that the (external) blosc libary has **runtime** avx2 and sse2 support:

from the build log ([travis](https://s3.amazonaws.com/archive.travis-ci.org/jobs/160416283/log.txt))
```
-- Building for system processor i686
-- Adding run-time support for SSE2
-- Adding run-time support for AVX2
``` 
 
@FrancescAlted : Am I correct in assuming blosc has **runtime** avx2 support (does that mean that it runs on a CPU without avx2 when compiled on an avx2 enabled machine??)

I'm currently travelling, but I intend to fix this when I get back by building the wheels with the external blosc, to prevent the `-mavx2` cflags when compiling cython extensions.

**Comment by FrancescAlted** [comment]
Yes, you are correct in that Blosc has runtime AVX2 support detection in that the shuffle/bitshuffle routines will not be called on a non-AVX2 machine (and the same happens with SSE2).  However, the problem here is that the `-mavx2` flag makes the compiler to spit AVX2 instructions somewhere else (like in the  `hdf5extension.so`, as you detected).

I suggest to use the easy workaround for this: just use the `-mnoavx2` flag (this should have precedence towards `-mavx2`) when generating the wheels.  This way, only people compiling PyTables from their own machine (i.e. natively) will get benefited from using AVX2 (if available); however, AVX2 is not buying you that much speed-up, so I don't think this would be too bad.

Finally, I don't think the current handling of `-msse2` and `-mavx2` flags in setup.py is inconsistent.  These are needed (well, maybe `-msse2` is not) for generating an internal Blosc with support for AVX2.  Having said that, if you find a better solution, feel free ;)

**Comment by tomkooij** [comment]
I build the manylinux wheels with `-mno-avx2` in CFLAGS. I tested these on a recent CPU without AVX2 and the tests run fine. I pushed the wheels to PyPI.

I was about to close this, but I tried the wheels on a `Intel(R) Celeron(R) CPU  N2830  @ 2.16GHz` (BayTrail 2014) and I get a SIGILL right away. This CPU does not have AVX (the other does have AVX), but I'm seeing no AVX instruction with `objdump`. The 3.4.0 wheels (build without `-mavx2`) run fine on the celeron.

I will probably revert back to building separate blosc library for the manylinux wheels (Which I do not prefer, because I need to manually update the blosc version for each new pytables build). In a next release we can disable the `-mavx2` flags for wheel building.

Any ideas?

**Comment by FrancescAlted** [comment]
Yes, my guess is that, despite what objdump is saying, GCC is still spitting AVX instructions (but not AVX2).  I'd try to use either `-mno-avx` or better `-march=core2`.  The Core2 architecture is more than 10 years old, so I'd say that this should be considered safe for more than 99% of the Intel/AMD computers out there (the owners of the remaining <1% should compile for themselves).

**Comment by tomkooij** [comment]
I agree that building for core2 architure should be fine.
 
I'll try `-march=core2`. Let's hope than overrules the AVX/AVX2 instructions.

In the meantime, I have uploaded working manylinux wheels build using the "old" method, with external (outdated) blosc.

**Comment by tomkooij** [comment]
`-march=core2` --> still illegal instruction.

I'm done with fiddling with these compiler flags. I'm reverting back to the old wheels with external blosc.

**Comment by tomkooij** [comment]
New manylinux wheels on PyPI. 

Should be fixed now.

**Comment by tomkooij** [comment]
Fixed (using internal c-blosc) by applying https://github.com/MacPython/pytables-wheels/commit/45933ee86c94bae440158d4d29ff659dcfe7cf43
