### ISSUE TITLE
ROFileNode fails to return the fileno()

### ISSUE THREAD

**Issue by pgruenbacher** [PyTables/PyTables#633]
https://github.com/PyTables/PyTables/blob/6782047b9223897fd59ff4967d71d7fdfb474f16/tables/nodes/filenode.py#L148-L158

I found this issue when I was trying to have django serve files from an h5 table by individually reading in nodes. Gunicorn expects the file-like object to return a fileno(). It's clear the method isn't returning the underlying node fileno()

**Comment by marfel** [comment]
Ok, I just stumbled over this too. Since it apparently hasn't occurred to anyone else in the last three years, and it hasn't been fixed either (by simply inserting a `return`), am I to assume the `filenode` extension is officially dead now?

I was trying to use `filenode`s to save PyTorch nets in the h5 tree, using `torch.load` and `torch.save`. However, there must be another bug somewhere in the `filenode` class: While no errors occurred during saving, the resulting HDF5 file was always corrupted. Manually saving the net to a `BytesIO` buffer and then storing it in a `CArray` or `EArray` node caused no difficulties.

**Comment by avalentino** [comment]
Hi @marfel  i prepared the patch (tests are currently running) and i plan to merge it ASAP.
The fix should be in the next PyTables release.
Regarding other issues you are experimenting please feel free to open a new issue with some information on how to reproduce.
