### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by maxnoe** [PyTables/PyTables#826]
There are some bug fixes in the current master that would be nice to have in a release.

Since the last point release is over a year old, could you maybe make a 3.6.2?

**Comment by maxnoe** [comment]
This is getting more urgent for use. It's been 1.5 years with many bug fixes. Anything we can do to help?

**Comment by avalentino** [comment]
Hi @maxnoe, yes you are right we should make a release as soon as possible.
Apart for the chronic lack of maintainers time, on the technical side IMHO there is a blocking issue:
at the moment I'm afraid that we are not able to release a reasonable set of wheels

There is some WIP PR (see e.g. #872) but the work seems to be stalled at the moment.

> Anything we can do to help?

If you want to contribute it would be very appreciated.
For a new release the main area of activity are:
* reviewing currently open issue to identify the ones that absolutely need to be in the next release (a list of links in the description of this issue would be nice)
* help with the setup of the wheel infrastructure (see above)
* make sure that pytables correctly works with latest Python, numpy, HDF5 (this is basically a CI stuff)
* check/update the documentation if needed and the release notes

**Comment by Chronial** [comment]
Christoph Gohlke provides pytables wheels for windows and python 3.8 and 3.9 at https://www.lfd.uci.edu/~gohlke/pythonlibs/#pytables.
Would it be an option to ask him for Permission and add these wheels to pypi?

**Comment by aufdenkampe** [comment]
Any updates on a timeline for a new release?

I'm particularly interested support for HDF5 v1.12, which has substantial performance and other benefits over v1.10 (it releases the GIL!), in addition to other benefits such as better handling of datetime and strings.

Furthermore, [h5py](https://github.com/h5py) has supported HDF5 v1.12 since their v3.0 release in October, 2020, and just released their v3.1 which supports HDF5 v1.12.1.

Our watershed modeling system presently uses both Pytables via Pandas and also h5py, and we have observed many issues when the two use different versions of HDF5. See https://github.com/respec/HSPsquared/issues/36. 

We're about to embark on rebuilding the model I/O infrastructure and need to decide if we stick with Pytables or not. https://github.com/respec/HSPsquared/issues/59

**Comment by avalentino** [comment]
PyTables v3.7.0 is now available.
