### ISSUE TITLE
Inconsistent package naming between pypi.org and Condaforge

### ISSUE THREAD

**Issue by CharlesB2** [PyTables/PyTables#886]
This is a minor issue only, but I find unpratical that the package is named differently between [condaforge (`pytables`)](https://anaconda.org/conda-forge/pytables) and [pypi.org (`tables`)](https://pypi.org/project/tables/). 

I don't know if one these repositories allows having aliases, but I guess it's possible only with condaforge since pypi.org already has a `pytables` project registered.

**Comment by avalentino** [comment]
Hi @CharlesB2 sorry for the late reply.
This is an interesting comment. Do you have a pointer to relevant documentation that explains how aliases work in confa-forge and how to create them?
Also since the problem mainly regards the conda package you may want to open a corresponding issue on that repository [1].

[1] https://github.com/conda-forge/pytables-feedstock

**Comment by CharlesB2** [comment]
Thanks, actually the issue is already up at https://github.com/conda-forge/pytables-feedstock/issues/54. Shall I close this one?

**Comment by avalentino** [comment]
@CharlesB2 thanks for linking the issue.
It seems there is nothing else we can do on pytables *core*, so I'm closing the issue.
