### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [PyTables/PyTables#891]
Problem
---------
On aarch64, pip install PyTables builds the wheels from source code and then install it. It requires user to have development environment installed on his system. also, it take some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, pip install PyTables should download the wheels from pypi

@avalentino, please let me know your interest on releasing aarch64 wheels. I can help in this.

**Comment by aufdenkampe** [comment]
A release supporting AArch64 or ARM64 architecture that is increasingly in use by cloud providers such as Amazon Web Services (AWS), in large part because it is much more power efficient. AWS passes that power savings to customers with a 40% greater power to cost ratio.

Supporting AArch64 or ARM64 will be a requirement for future cloud computing. It also helps mitigate climate change by substantially decreasing energy usage.

**Comment by avalentino** [comment]
Fixed in #892 and #918. Closing.
