### ISSUE TITLE
Library not loaded: @rpath/libblosc.1.dylib

### ISSUE THREAD

**Issue by sophievincoff** [PyTables/PyTables#901]
Hello, I am working in a virtual environment on a Jupyter notebook. tables installs without error, but when I run `import tables` or `python3 -m tables.tests.test_all`, I receive this error:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/gv/Desktop/Appyter/my-first-appyter-2/venv/lib/python3.9/site-packages/tables/__init__.py", line 99, in <module>
    from .utilsextension import (
ImportError: dlopen(/Users/gv/Desktop/Appyter/my-first-appyter-2/venv/lib/python3.9/site-packages/tables/utilsextension.cpython-39-darwin.so, 2): Library not loaded: @rpath/libblosc.1.dylib
  Referenced from: /Users/gv/Desktop/Appyter/my-first-appyter-2/venv/lib/python3.9/site-packages/tables/utilsextension.cpython-39-darwin.so
  Reason: image not found

I tried `python3 -m pip install blosc` and moved blosc into the **tables** directory, but that did not fix the issue. I also tried `pip install -U --force-reinstall --no-binary tables tables`. I would greatly appreciate any help! Thanks!

**Comment by avalentino** [comment]
@sophievincoff , @selasley , in principle you should have a symlink `libblosc.1.dylib --> libblosc.1.21.1.dylib` in `/usr/local/lib`, so not clear to me what exactly is the problem.

Are you using a pre-build version of blosc or are you building form sources the vendored one?
More inofrmation about the environment, the build procedure and logs would be appreciated.

I assume the first option (pre-built `blosc`) because in the `setup.py` of PyTables `rpath` is never set.
In this case you should eventually report the issue to https://github.com/Blosc/c-blosc.

**Comment by avalentino** [comment]
Fixed in #927.
