### ISSUE TITLE
Access to a protected member _v_attrs and _f_list

### ISSUE THREAD

**Issue by jpjarnoux** [PyTables/PyTables#949]
Hi, I would to know if there is a method to access to this attribute ? I don't find any.

If not, it could be a good thing to add one to access to a protected member.

Thanks

**Comment by avalentino** [comment]
Dear @jpjarnoux thanks for reporting.
This is indeed a weak part of our documentation probably.
The short answer is that, despite the name starts with an underscore, they are not considered private and, indeed, they are regularly documented in our reference documentation.

The reason why you may have attributes with names like the following `_?_xxx` is that PyTables implements a "natural naming" mechanism to map different elements contained in the HDF5 file in our data model.

For this reason if the root group includes a dataset `d` and a sub-group `g` you can write in your code `root.d` or `root.g`.

Since there was the need to distinguish "standard" attributes (belonging to the PyTables API) form the ones coming form the content of HDF5 files the `_?_xxx` notation has been introduced.

Unfortunately I do not remember the exact meaning for various prefixes `_f_`, `_g_`, `_v_`, etc. (probably "file", "group", "variable", etc).
I don't thing that it is documented anywhere.
Maybe @FrancescAlted can provide more clarifications.

**Comment by jpjarnoux** [comment]
Hi, 
Thanks for your complete answer. I understand better the needed to use this notation.
Thank you.
