### ISSUE TITLE
PyTables crash with SIGILL due to unsupported AVX instruction set in some cpus

### ISSUE THREAD

**Issue by kartlee** [PyTables/PyTables#956]
We are using pytable 3.6.1 compiled from source with custom hdf5 linked during the build. For mac, the libraries are built in 10.14 in intel. And for linux, the library gets built in centos 7.9.  

We are noticing crash due to SIGILL when using under M1 mac and few linux machines running 'Intel(R) Xeon(R) CPU E5345'. 

I am planning to set DISABLE_AVX2=1  and build 3.6.1 version of the library for darwin, linux and mac. Does that sound good to you folks?  If you can add this fix to 3.6.1 by default, that might be great. Otherwise, can you please make sure its available for higher versions when we planned to upgrade?

**Comment by avalentino** [comment]
Dear @kartlee,
the PyTables setup script has a mechanism to detect CPU features and enable/disable build flag to achieve the best performance on the build machine.

Of course if features like e.g. the support to AVX2 instruction are enabled at build time, the resulting binary package shall be used on compatible machines and it is not expected to work on HW that do not support the very same CPU features.

(probably I have not correctly interpreted your message in https://github.com/PyTables/PyTables/issues/841#issuecomment-1191993365)

If you plan to build on a machine and tun PyTables on a different one then you need to ensure to use the proper flags in the build process to ensure compatibility with the target machine. This is what packagers normally do and this is the recommended way to proceed at te moment.

Regarding the possibility to change the default build configuration to privilege portability over computational speed, this is something that can be considered for future releases but we need to consider also drawbacks. At the moment I do not see new strong points to change the current behaviour but I'm open to discussion.

Since what you are reporting is mostly expected I think that this issue can be closed, unless you wan to keep it as a memo for the possible future change in the default build behaviour. In this case please modify the title accordingly.

**Comment by kartlee** [comment]
We build the wheels in a machine for each platform, and use it across all CPUs of the supported platforms. What sort of performance degrade we would see when turning of AVX2 completely?

-Karthik

**Comment by avalentino** [comment]
It mostly depends on the PyTables features that you use.
AVX2 should be mostly used for in the expression evaluator and in compression filters.
If you do not use heavily that features probably you will not have any performance degradation.
My recommendation, anyway, is to perform some benchmarks and evaluate directly the impact.

**Comment by kartlee** [comment]
sounds good, thanks. You can close this ticket. And thanks for explaining me the background of the usage.

**Comment by kartlee** [comment]
We just use for limited purpose, and doesn't involve the usage you mentioned. Just fyi.

**Comment by avalentino** [comment]
Thanks @kartlee
